# Setup Cluster

- name: Install kubectl on Master
  apt:
    name: kubectl
    state: present

# Initialize Cluster. The log is also used to prevent an second initialization
- name: Initialize Cluster
  shell: kubeadm init --pod-network-cidr=10.10.0.0/16 --apiserver-advertise-address=192.168.5.11 >> cluster_init.log
  args:
    chdir: $HOME
    creates: cluster_init.log

# Wait for kubeadm to complete initialization of cluster
- name: Wait for kubeadm to complete initialization
  wait_for: "host={{ hostvars['lab-k8s-master']['ansible_default_ipv4']['address'] }} port=6443 delay=10"
 
# Create the configuration / configuration directory
- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to the user's kube directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: Setup Weavenetwork. Use log to prevent second installation
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >> weave_setup.log
  args:
    chdir: $HOME
    creates: flannel_setup.log

- name: Create token to join cluster
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command as fact
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"