---
- hosts: target
  tasks:
    - name: deploy dependency app
      copy:
        src: /var/lib/jenkins/workspace/final-pipeline/java-tomcat-maven-example/target/dependency/webapp-runner.jar
        dest: /home/jenkins/
    - name: deploy application
      copy:
        src: /var/lib/jenkins/workspace/final-pipeline/java-tomcat-maven-example/target/java-tomcat-maven-example.war
        dest: /home/jenkins/
    - name: start the app
      shell: 'nohup java -jar /home/ansible/*.jar /home/ansible/*.war &'
